export const MOCK_EVENTS = [
{
    id: '1',
    title: 'Concert Jazz au Vieux-Port',
    category: 'musical',
    latitude: 45.5088,
    longitude: -73.5540,
    date: '2026-03-20',
    heure: '20h00',
    lieu: 'Vieux-Port de Montréal',
    prix: '25$',
    description: 'Une soirée jazz en plein air au cœur du Vieux-Port.',
},
{
    id: '2',
    title: 'Match du Canadien',
    category: 'sportif',
    latitude: 45.4961,
    longitude: -73.5694,
    date: '2026-03-21',
    heure: '19h30',
    lieu: 'Centre Bell',
    prix: '80$',
    description: 'Canadiens de Montréal vs Toronto Maple Leafs.',
},
{
    id: '3',
    title: 'Brunch Le Cartet',
    category: 'restaurant',
    latitude: 45.5051,
    longitude: -73.5530,
    date: '2026-03-22',
    heure: '10h00',
    lieu: 'Rue McGill, Montréal',
    prix: '20$',
    description: 'Brunch gastronomique dans le Vieux-Montréal.',
},
{
    id: '4',
    title: 'Expo Musée des Beaux-Arts',
    category: 'musee',
    latitude: 45.4985,
    longitude: -73.5795,
    date: '2026-03-23',
    heure: '11h00',
    lieu: 'Musée des Beaux-Arts, Montréal',
    prix: '15$',
    description: 'Exposition temporaire sur l\'art contemporain québécois.',
},
{
    id: '5',
    title: 'Café Spécialité Saint-Henri',
    category: 'cafe',
    latitude: 45.4724,
    longitude: -73.5812,
    date: '2026-03-20',
    heure: '08h00',
    lieu: 'Saint-Henri, Montréal',
    prix: '5$',
    description: 'Café de spécialité torréfié sur place.',
},
{
    id: '6',
    title: 'Festival Électro MTL',
    category: 'musical',
    latitude: 45.5120,
    longitude: -73.5620,
    date: '2026-03-25',
    heure: '22h00',
    lieu: 'Quartier des spectacles',
    prix: '40$',
    description: 'Festival de musique électronique au cœur de Montréal.',
},
{
    id: '7',
    title: 'Tournoi Basketball UQAM',
    category: 'sportif',
    latitude: 45.5093,
    longitude: -73.5689,
    date: '2026-03-22',
    heure: '14h00',
    lieu: 'UQAM, Montréal',
    prix: 'Gratuit',
    description: 'Tournoi inter-universitaire de basketball.',
},
];